name: Qualité de code
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Installer PHPCS
        run: |
          sudo apt-get update
          sudo apt-get install php-codesniffer
      - name: Vérifier le code avec PHPCS
        run: phpcs src/
