name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Mis à jour de v2 à v4 pour cohérence

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      run: vendor/bin/phpcs

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-html coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v4  # Changé de v3 à v4
      with:
        name: coverage-report
        path: coverage/
